apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-k8s-app
  labels:
    app: nextjs-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-k8s-app
  template:
    metadata:
      labels:
        app: nextjs-k8s-app
    spec:
      containers:
        - name: nextjs-app
          image: elizaldecruzm/nextjs-k8s-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_VERSION
              value: "1.0.0"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-k8s-service
spec:
  selector:
    app: nextjs-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
