apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  containers:
    - name: load-generator
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do wget -q -O- http://nextjs-k8s-service/api/cpu-work; sleep 0.1; done",
        ]
  restartPolicy: Never
